#pragma once

// High-level wrappers for Bambu's cloud auth endpoints.
//
// Studio drives the interactive sign-in through its own wxWebView /
// system-browser flow and hands the resulting tokens back via
// `bambu_network_change_user` (see Agent::apply_login_info). On our
// side we only need:
//   * a ticket->token exchange (for the "system browser" callback),
//   * a refresh_token rotation (to keep the session alive), and
//   * a profile fetch (uid / nickname / avatar).
// The global host is `api.bambulab.com`, with a CN mirror at
// `api.bambulab.cn`.

#include <cstdint>
#include <string>
#include <vector>

namespace obn::cloud {

struct AuthResult {
    bool        ok           = false;
    long        http_status  = 0;
    std::string raw_body;       // server response body (verbatim); we keep it so
                                // Studio-side code that expects the JSON shape
                                // of "login_info" gets the real thing.
    std::string access_token;
    std::string refresh_token;
    long        expires_in         = 0; // seconds until access_token dies, as reported
    long        refresh_expires_in = 0; // seconds until refresh_token dies, as reported
    std::string login_type;      // "", "verifyCode", "tfa"
    std::string tfa_key;         // present when login_type == "tfa"
    std::string error_message;   // human-readable; populated on !ok
};

struct ProfileResult {
    bool        ok           = false;
    long        http_status  = 0;
    std::string raw_body;
    std::string user_id;
    std::string user_name;
    std::string nick_name;
    std::string avatar;
    std::string account;    // email
    bool        firmware_beta_open = false; // setting.isFirmwareBetaOpen
    std::string error_message;
};

// Endpoint host helpers. `region` is "CN" or anything else (global).
//   api_host  -> REST API base, e.g. "https://api.bambulab.com" (no slash).
//   web_host  -> portal base Studio injects into wxWebView, e.g.
//                "https://bambulab.com/" (WITH trailing slash). Studio
//                concatenates different suffixes onto this base
//                ("/sign-in", "api/sign-in/ticket?..." without a leading
//                slash, "/<lang>/sign-in"). The trailing slash on our side
//                is mandatory - otherwise "host + api/..." produces
//                "bambulab.comapi/..." and DNS fails.
std::string api_host(const std::string& region);
std::string web_host(const std::string& region);

// Ticket-exchange: the "system browser" / wxWebView login lands on the
// local HTTP server Studio stands up and hands us a short-lived
// `ticket`. We POST it to /v1/user-service/user/ticket/<TICKET> (the
// body is ignored) and the server replies with accessToken /
// refreshToken. On success the populated AuthResult's raw_body is the
// JSON Studio feeds back into `bambu_network_change_user`.
AuthResult login_with_ticket(const std::string& region,
                             const std::string& ticket);

AuthResult refresh_token(const std::string& region,
                         const std::string& refresh_token);

ProfileResult get_profile(const std::string& region,
                          const std::string& access_token);

// NOT YET WIRED - the following struct and function document the cloud MQTT
// mTLS certificate endpoint. The implementation in cloud_auth.cpp is gated
// with #if 0. See agent.cpp install_device_cert for the integration plan.
//
// Result of fetching the cloud MQTT client certificate for a device.
// The cert chain contains three PEM blocks: device leaf, per-device
// intermediate CA named "{dev_uid}.bambulab.com", and the root CA.
// The private key is AES-256-CBC encrypted; the caller must decrypt it
// with the same aes256_key passed to fetch_device_cert().
struct DeviceCertResult {
    bool        ok          = false;
    long        http_status = 0;
    std::string raw_body;
    std::string cert;          // PEM chain: device leaf + intermediate + root
    std::string crl;           // PEM CRL from crl[0] array entry, valid ~30 days from issue
    std::string key;           // AES-256-CBC encrypted private key, base64-encoded
    std::string error_message;
};

// Fetch the cloud MQTT mTLS client certificate for a device.
//
// `application_token` - session-scoped token generated by the stock plugin and
// stored in BambuNetworkEngine.conf. It rotates between login sessions and is
// distinct from the printer dev_id. Derivation from the stock binary is not
// yet confirmed; pass the value retrieved from the active session config.
//
// `aes256_key` - caller-generated random 32-byte key, base64url-encoded.
// The server uses it to encrypt the returned private key. The caller must
// base64url-decode this key and use AES-256-CBC to decrypt
// DeviceCertResult::key before the private key can be used with mosquitto.
DeviceCertResult fetch_device_cert(const std::string& region,
                                   const std::string& access_token,
                                   const std::string& application_token,
                                   const std::string& aes256_key);

} // namespace obn::cloud
